version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_TYPE=$DATABASE_TYPE
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_HOST=$DATABASE_HOST
      - DATABSE_PORT=$DATABASE_PORT
    env_file:
      - .env
    volumes:
      - ./:/usr/app
  
  postgres:
    image: postgres:12.12-alpine
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: